export { default as CofinHome } from 'features/home/components/CofinHome'
export { default as Header } from 'features/common/components/Header'
export { default as LayOut } from 'features/common/components/LayOut'
export { default as Footer } from 'features/common/components/Footer'
export { default as Login } from 'features/common/components/Login'
export {default as Icon } from 'features/common/components/Icon'
export { default as Navi } from 'features/common/components/Navi'